import Head from 'next/head';

//React & Next.js Components
import Header from '../components/Header';
import { HeroSection, AboutSection } from '../components/Home';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bradley Mubenga | Web Developer, Leader, Human.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="fpParentElement">
        <Header />
        <HeroSection />
        <AboutSection />
      </main>
    </>
  )
}
