import Head from 'next/head';

//React & Next.js Components
import Header from '../components/Header';
import { HeroSection, AboutSection, RecentProjects, ContactForm } from '../components/Home';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bradley Mubenga | Web Developer, Leader, Human.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />

      <main className="fpParentElement">
        <HeroSection />
        <AboutSection />
        <RecentProjects />
        <ContactForm />
      </main>
    </>
  )
}